apiVersion: apps/v1
kind: Deployment
metadata:
  name: transcribe-frontend
  namespace: transcribe-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transcribe-frontend
  template:
    metadata:
      labels:
        app: transcribe-frontend
    spec:
      containers:
      - name: transcribe-frontend
        image: harbor.infrastructure.cloudnative.nvdlab.net/wolfgang/transcribe-frontend:0.1.0
        imagePullPolicy: Always
        env:
        - name: DATABASE_URL
          value: postgresql://postgres:postgres@10.122.7.94/flowise_ndb
        - name: OPENAI_TOKEN
          value: 415c846c-553f-4e8e-bc61-9ef0b37b1b88
        - name: BASE_URL
          value: https://nai.wh-nkp-nai-stage.cloudnative.nvdlab.net/api/v1
        resources:
          requests:
            cpu: 2
            memory: 4Gi
            nvidia.com/gpu: 1
          limits:
            cpu: 2
            memory: 4Gi
---
apiVersion: v1
kind: Service
metadata:
  name: transcribe-frontend-service
  namespace: transcribe-demo
spec:
  selector:
    app: transcribe-frontend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8504
      targetPort: 8504
---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: frontend-ingress
#   namespace: transcribe-demo
#   annotations:
#     cert-manager.io/cluster-issuer: letsencrypt-prod
#     nginx.ingress.kubernetes.io/proxy-body-size: 500M
# spec:
#   ingressClassName: "nginx"
#   rules:
#   - host: frontend.gpt01dev01.cloudnative.nvdlab.net
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: frontend-service
#             port:
#               number: 8000
#   tls:
#   - hosts:
#     - frontend.gpt01dev01.cloudnative.nvdlab.
#     secretName: frontend-tld-secret